export const versions = {
  latest: 'imwss3',
  releases: [
    'glider-rc.1',
    'glider',
    'auburn-glider',
    'burgundy-glider',
    'lwss',
    'clwss',
    'dlwss',
    'elwss',
    'elwss2',
    'elwss3',
    'flwss',
    'flwss2',
    'flwss3',
    'glwss',
    'glwss2',
    'glwss3',
    'glwss4',
    'hmwss',
    'imwss',
    'imwss2',
    'imwss3',
  ],
  releaseMap: {
    IColony: {
      'glider-rc.1': 1,
      glider: 2,
      'auburn-glider': 3,
      'burgundy-glider': 4,
      lwss: 5,
      clwss: 6,
      dlwss: 7,
      elwss3: 8,
      flwss: 9,
      glwss: 10,
      glwss2: 11,
      glwss3: 12,
      glwss4: 13,
      hmwss: 14,
      imwss: 15,
      imwss2: 16,
      imwss3: 17,
      next: 18,
    },
    CoinMachine: {
      clwss: 1,
      dlwss: 2,
      elwss2: 3,
      elwss3: 4,
      flwss: 5,
      glwss: 6,
      glwss2: 7,
      glwss4: 8,
      hmwss: 9,
      imwss: 10,
      imwss2: 11,
      imwss3: 12,
      next: 13,
    },
    EvaluatedExpenditure: {
      elwss: 1,
      flwss: 2,
      glwss2: 3,
      glwss4: 4,
      hmwss: 5,
      imwss: 6,
      imwss2: 7,
      imwss3: 8,
      next: 9,
    },
    FundingQueue: {
      lwss: 1,
      dlwss: 2,
      flwss: 3,
      glwss2: 4,
      glwss4: 5,
      hmwss: 6,
      imwss: 7,
      imwss2: 8,
      imwss3: 9,
      next: 10,
    },
    IVotingReputation: {
      flwss3: 6,
      glwss: 7,
      glwss2: 8,
      glwss4: 9,
      hmwss: 10,
      imwss: 11,
      imwss2: 12,
      imwss3: 13,
      next: 14,
    },
    MultisigPermissions: {
      imwss2: 1,
      imwss3: 2,
      next: 3,
    },
    OneTxPayment: {
      clwss: 1,
      dlwss: 2,
      flwss: 3,
      glwss2: 4,
      glwss4: 5,
      hmwss: 6,
      imwss: 7,
      imwss2: 8,
      imwss3: 9,
      next: 10,
    },
    ReputationBootstrapper: {
      glwss2: 1,
      glwss4: 2,
      hmwss: 3,
      imwss: 4,
      imwss2: 5,
      imwss3: 6,
      next: 7,
    },
    StagedExpenditure: {
      hmwss: 1,
      imwss: 2,
      imwss2: 3,
      imwss3: 4,
      next: 5,
    },
    StakedExpenditure: {
      glwss: 1,
      glwss2: 2,
      glwss4: 3,
      hmwss: 4,
      imwss: 5,
      imwss2: 6,
      imwss3: 7,
      next: 8,
    },
    StreamingPayments: {
      glwss: 1,
      glwss4: 2,
      hmwss: 3,
      imwss: 4,
      imwss2: 5,
      imwss3: 6,
      next: 7,
    },
    TokenSupplier: {
      lwss: 1,
      dlwss: 2,
      flwss: 3,
      glwss2: 4,
      glwss4: 5,
      hmwss: 6,
      imwss: 7,
      imwss2: 8,
      imwss3: 9,
      next: 10,
    },
    VotingReputation: {
      clwss: 1,
      dlwss: 2,
      elwss: 3,
      flwss: 4,
      flwss2: 5,
    },
    Whitelist: {
      elwss: 1,
      flwss: 2,
      glwss2: 3,
      glwss4: 4,
      hmwss: 5,
      imwss: 6,
      imwss2: 7,
      imwss3: 8,
      next: 9,
    },
  },
} as const;
