name: Release a snapshot

on:
  # Only manual workflow trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Cache NPM dependencies
        uses: actions/cache@v4
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: pnpm install --frozen-lockfile

      - name: Install dependencies for colonyNetwork
        working-directory: ./vendor/colonyNetwork
        run: npm ci

      - name: Compile colonyNetwork contracts
        working-directory: ./vendor/colonyNetwork
        run: npx hardhat compile

      - run: npm run build
